"""Autonomous navigation simulator (waypoint follower + dock management).

The robot follows a cleaning route through the facility. Routes can be:
1. Fixed (legacy): hardcoded waypoints loaded from config
2. Dynamic (mission): generated by the coverage planner, following
   farthest-first room order with boustrophedon lane coverage

While following, a simple P-controller on the heading error produces
differential-drive wheel commands. When the engine requests service,
the navigator switches to the charging dock; when resumed, it continues
from the exact waypoint it was interrupted at - mirroring a ROS2
``FollowWaypoints`` behaviour tree.
"""
from __future__ import annotations

import math
import random
from dataclasses import dataclass
from typing import Callable, List, Optional, Tuple

from app.core.config import Config
from app.sim.state import Pose, clamp, wrap_angle


@dataclass
class Waypoint:
    x: float
    y: float
    label: str


@dataclass
class DriveCommand:
    left: float  # left wheel speed [m/s]
    right: float  # right wheel speed [m/s]
    target_label: str
    driving: bool
    heading_error_rad: float = 0.0


class NavigationSimulator:
    """Pure waypoint-following controller (no map planarity assumptions)."""

    MODE_CLEANING = "cleaning"
    MODE_DOCK = "dock"

    def __init__(
        self,
        config: Config,
        rng: random.Random,
        coverage_progress_fn: Optional[Callable[[], float]] = None,
        can_move_check_fn: Optional[Callable[[float, float, float, float, float], bool]] = None,
    ) -> None:
        nav_cfg = config.navigation
        clean_cfg = config.cleaning
        robot_cfg = config.robot

        self._clean_route: list[Waypoint] = [
            Waypoint(x=x, y=y, label=label)
            for (x, y, label) in nav_cfg.cleaning_route
        ]
        self._dock = Waypoint(
            x=nav_cfg.dock_position[0],
            y=nav_cfg.dock_position[1],
            label="Charging dock",
        )
        self._tolerance = nav_cfg.waypoint_tolerance
        self._transit_tolerance = getattr(nav_cfg, 'transit_waypoint_tolerance', 0.10)
        self._cleaning_tolerance = getattr(nav_cfg, 'cleaning_waypoint_tolerance', 0.12)
        self._base_speed = clean_cfg.base_speed
        self._turn_gain = clean_cfg.turn_gain
        self._approach = clean_cfg.approach_slowdown
        self._max_speed = robot_cfg.max_speed
        self._max_turn = robot_cfg.max_turn_rate
        self._wheel_base = robot_cfg.wheel_base
        self._rng = rng

        self._coverage_progress_fn = coverage_progress_fn
        self._can_move_check_fn = can_move_check_fn
        self._mission_route: Optional[List[Waypoint]] = None

        # progressive state
        self.mode = NavigationSimulator.MODE_CLEANING
        self.index = 0  # index into the full cleaning route
        self.cleaned_meters = 0.0
        self.lap = 1
        self.laps_completed = 0
        self.dock_reached = False
        self._last_arrival: Optional[Tuple[float, float]] = None
        self._total_route_length = self._route_length()

    def set_mission_route(self, waypoints: List[Waypoint]) -> None:
        """Set a dynamically generated mission route.

        The mission replaces the fixed cleaning_route for the current
        cleaning session. When the mission completes (index >= len),
        cleaning_progress returns 100% if coverage_fn reports 100%.
        """
        if not waypoints:
            return
        self._mission_route = waypoints
        self.mode = NavigationSimulator.MODE_CLEANING
        self.index = 0
        self.cleaned_meters = 0.0
        self.lap = 1
        self.laps_completed = 0
        self.dock_reached = False
        self._last_arrival = None
        self._total_route_length = self._mission_route_length()

    def _effective_route(self) -> List[Waypoint]:
        """Return mission route if set, else the fixed cleaning route."""
        if self._mission_route is not None:
            return self._mission_route
        return self._clean_route

    def _mission_route_length(self) -> float:
        """Total length of the mission route in metres."""
        if self._mission_route is None:
            return self._route_length()
        total = 0.0
        for i in range(len(self._mission_route) - 1):
            a, b = self._mission_route[i], self._mission_route[i + 1]
            total += math.hypot(b.x - a.x, b.y - a.y)
        return total if total > 0.0 else 1.0

    # ------------------------------------------------------------------
    # metrics
    # ------------------------------------------------------------------
    def _route_length(self) -> float:
        total = 0.0
        for i in range(len(self._clean_route) - 1):
            a, b = self._clean_route[i], self._clean_route[i + 1]
            total += math.hypot(b.x - a.x, b.y - a.y)
        return total if total > 0.0 else 1.0

    def cleaning_progress(self) -> float:
        """Coverage progress 0..100.

        If a coverage progress callback was provided (area-based), that
        takes priority. Otherwise falls back to lap-distance-based progress.
        """
        if self._coverage_progress_fn is not None:
            return self._coverage_progress_fn()

        route_len = self._mission_route_length() if self._mission_route else self._total_route_length
        if route_len <= 0.0:
            return 100.0
        within_lap = self.cleaned_meters % route_len
        return clamp(within_lap / route_len * 100.0, 0.0, 100.0)

    def current_label(self) -> str:
        if self.mode == NavigationSimulator.MODE_DOCK and not self.dock_reached:
            return "Returning to charging dock"
        if self.mode == NavigationSimulator.MODE_DOCK and self.dock_reached:
            return "At charging dock"
        route = self._effective_route()
        if self.index >= len(route):
            if self._mission_route is not None:
                return "Mission complete"
            return "Completing lap"
        return route[self.index].label

    def reset_route(self) -> None:
        """Restart the cleaning route from its first waypoint."""
        self.mode = NavigationSimulator.MODE_CLEANING
        self.index = 0
        self.cleaned_meters = 0.0
        self.lap = 1
        self.laps_completed = 0
        self.dock_reached = False
        self._last_arrival = None
        self._mission_route = None

    def return_to_dock(self) -> None:
        """Switch navigation to the charging dock."""
        if self.mode != NavigationSimulator.MODE_DOCK:
            self.mode = NavigationSimulator.MODE_DOCK
            self.dock_reached = False

    def resume_cleaning(self) -> None:
        """Resume the cleaning route at the interrupted waypoint."""
        self.mode = NavigationSimulator.MODE_CLEANING
        self.dock_reached = False

    def current_segment_mode(self) -> str:
        """Return the current movement segment mode.

        Possible values:
        - "dock": robot is returning to or at the charging dock
        - "transit": robot is traversing a transit connector waypoint
        - "cleaning": robot is following an active cleaning segment
        """
        if self.mode == NavigationSimulator.MODE_DOCK:
            return "dock"
        route = self._effective_route()
        if self.index < len(route) and self._is_transit_waypoint(route[self.index]):
            return "transit"
        return "cleaning"

    def _is_transit_waypoint(self, waypoint: Waypoint) -> bool:
        """Return True if waypoint is a transit segment."""
        label_lower = waypoint.label.lower()
        return "transit" in label_lower or "dock" in label_lower

    def _get_waypoint_tolerance(self, waypoint: Waypoint) -> float:
        """Return appropriate tolerance for waypoint type."""
        if self.mode == NavigationSimulator.MODE_DOCK:
            return self._tolerance
        if self._is_transit_waypoint(waypoint):
            return self._transit_tolerance
        return self._cleaning_tolerance

    def _can_advance_safely(self, pose: Pose, route: List[Waypoint]) -> bool:
        """Check if it's safe to advance to the next waypoint.

        Uses can_move_check_fn to verify the path from current pose to next
        waypoint maintains required clearance. Returns False if next segment
        is unsafe, preventing premature waypoint advancement.
        """
        if self._can_move_check_fn is None:
            return True

        next_index = self.index + 1
        if next_index >= len(route):
            return True

        next_wp = route[next_index]
        if self._can_move_check_fn(pose.x, pose.y, next_wp.x, next_wp.y, 0.0):
            return True

        return False

    # ------------------------------------------------------------------
    # control
    # ------------------------------------------------------------------
    def step(self, pose: Pose) -> DriveCommand:
        """Compute wheel-speed commands for the current pose.

        Includes safe waypoint advancement guard - checks if next segment is safe
        before advancing from current waypoint. Uses tighter tolerance for transit
        segments to ensure accurate path tracking.
        """
        route = self._effective_route()
        if self.mode == NavigationSimulator.MODE_DOCK:
            target = self._dock
            if self.dock_reached:
                return DriveCommand(0.0, 0.0, target.label, driving=False)
        else:
            if self.index >= len(route):
                if self._mission_route is not None:
                    return DriveCommand(0.0, 0.0, "Mission complete", driving=False)
                self._complete_lap()
            target = route[self.index]

        dx, dy = target.x - pose.x, target.y - pose.y
        distance = math.hypot(dx, dy)

        tolerance = self._get_waypoint_tolerance(target)

        if distance < tolerance:
            if self._can_advance_safely(pose, route):
                self._handle_arrival(pose)
                return self.step(pose)
            else:
                pass

        desired_heading = math.atan2(dy, dx)
        heading_error = wrap_angle(desired_heading - pose.yaw)

        speed = self._base_speed
        if abs(heading_error) > 0.75:
            speed = 0.0
        elif abs(heading_error) > 0.30:
            speed = self._base_speed * 0.35

        if distance < self._approach:
            factor = clamp(distance / self._approach, 0.15, 1.0)
            speed *= factor

        linear = clamp(speed, -self._max_speed, self._max_speed)
        angular = clamp(
            self._turn_gain * heading_error, -self._max_turn, self._max_turn
        )

        left = linear - angular * self._wheel_base / 2.0
        right = linear + angular * self._wheel_base / 2.0
        limit = self._max_speed + self._max_turn * self._wheel_base / 2.0
        left, right = clamp(left, -limit, limit), clamp(right, -limit, limit)

        return DriveCommand(
            left=left,
            right=right,
            target_label=target.label,
            driving=True,
            heading_error_rad=heading_error,
        )

    # ------------------------------------------------------------------
    # internals
    # ------------------------------------------------------------------
    def _handle_arrival(self, pose: Pose) -> None:
        route = self._effective_route()
        if self.mode == NavigationSimulator.MODE_DOCK:
            self.dock_reached = True
            return

        was_cleaning_segment = False
        if self.index < len(route):
            was_cleaning_segment = not self._is_transit_waypoint(route[self.index])

        if was_cleaning_segment and self._last_arrival is not None:
            self.cleaned_meters += math.hypot(
                pose.x - self._last_arrival[0], pose.y - self._last_arrival[1]
            )
        self._last_arrival = (pose.x, pose.y)
        self.index += 1

        if self.index >= len(route):
            if self._mission_route is None:
                self._complete_lap()
            self._last_arrival = (pose.x, pose.y)

    def _complete_lap(self) -> None:
        self.laps_completed += 1
        self.lap = self.laps_completed + 1
        self.index = 0